/**
 * %%PROJECT_NAME%% -- starter app generated by Yujin Forge.
 *
 * Every interactive element here carries data-nac-id +
 * data-nac-role attributes. The NAC-3 runtime walks the DOM at
 * boot, registers the elements, and lets agents / the chat panel
 * drive them via verbs declared in src/nac/manifest.ts.
 */
import { useState } from 'react';

interface Todo {
  id: string;
  text: string;
  done: boolean;
}

export function App(): JSX.Element {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [input, setInput] = useState('');

  function addTodo() {
    const text = input.trim();
    if (text === '') return;
    setTodos((prev) => [...prev, { id: crypto.randomUUID(), text, done: false }]);
    setInput('');
  }

  function toggle(id: string) {
    setTodos((prev) => prev.map((t) => (t.id === id ? { ...t, done: !t.done } : t)));
  }

  function remove(id: string) {
    setTodos((prev) => prev.filter((t) => t.id !== id));
  }

  return (
    <main
      className="container"
      data-nac-id="todos.root"
      data-nac-role="region"
      data-nac-plugin="todos"
    >
      <h1>%%PROJECT_NAME%%</h1>
      <p className="hint">
        Built with <a href="https://yujin.app/nac-spec/">NAC-3</a> + Yujin Forge.
      </p>

      <div className="add-row">
        <input
          type="text"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter') addTodo(); }}
          placeholder="What needs doing?"
          data-nac-id="todos.input"
          data-nac-role="field"
          data-nac-field-kind="text"
        />
        <button
          type="button"
          onClick={addTodo}
          data-nac-id="todos.add_button"
          data-nac-role="action"
          data-nac-action="add_todo"
        >
          Add
        </button>
      </div>

      <ul
        className="list"
        data-nac-id="todos.list"
        data-nac-role="region"
      >
        {todos.length === 0 && <li className="empty">No todos yet.</li>}
        {todos.map((t) => (
          <li
            key={t.id}
            className={t.done ? 'done' : ''}
            data-nac-id={`todos.item.${t.id}`}
            data-nac-role="region"
          >
            <input
              type="checkbox"
              checked={t.done}
              onChange={() => toggle(t.id)}
              data-nac-id={`todos.item.${t.id}.done`}
              data-nac-role="action"
              data-nac-action="toggle_todo"
            />
            <span>{t.text}</span>
            <button
              type="button"
              onClick={() => remove(t.id)}
              data-nac-id={`todos.item.${t.id}.remove`}
              data-nac-role="action"
              data-nac-action="remove_todo"
            >
              ✕
            </button>
          </li>
        ))}
      </ul>
    </main>
  );
}
